version: '3.1'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ../pgdb/:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

networks:
  backend: